NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
import numpy as np

In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)


In [7]:
arr2 = arr1.reshape(5, 1) # 5 rows, 1 column

In [11]:
print(arr2)
print(arr2.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [15]:
# 2D array
arr2 = np.array([[1, 2, 3, 4, 5], [2,3,4,5,6]])
print(arr2.shape)
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]


In [16]:
np.arange(0,10,2) # start, stop, step

array([0, 2, 4, 6, 8])

In [17]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
arr = np.random.rand(3,3)

print("Array: \n", arr)    
print("Max: ", arr.max())
print("Min: ", arr.min())
print("Argmax: ", arr.argmax()) # index of max value
print("Argmin: ", arr.argmin()) # index of min value
print("Mean: ", arr.mean())
print("Std Dev: ", arr.std())
print("Shape:",arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)
print("Item Size: ", arr.itemsize)
print("Data: \n", arr.data)


Array: 
 [[0.2985394  0.37120528 0.65648389]
 [0.15563583 0.20555373 0.84714262]
 [0.41862018 0.74316754 0.51653358]]
Max:  0.8471426173863977
Min:  0.15563582571555956
Argmax:  5
Argmin:  3
Mean:  0.46809800473727314
Std Dev:  0.22713720780479493
Shape: (3, 3)
Dimension:  2
Size:  9
Data Type:  float64
Item Size:  8
Data: 


In [23]:
# vector operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element wise addition
print(f"Addition{arr1 + arr2}")
print(f"Subtraction{arr1 - arr2}")
print(f"Multiplication{arr1 * arr2}")
print(f"Division{arr1 / arr2}")


Addition[11 22 33 44 55]
Subtraction[ -9 -18 -27 -36 -45]
Multiplication[ 10  40  90 160 250]
Division[0.1 0.1 0.1 0.1 0.1]


In [25]:
# univeral functions
arr = np.array([1,2,3,4,5])
print(f"Sqrt{np.sqrt(arr)}")
print(f"Exp{np.exp(arr)}")  
print(f"Sin{np.sin(arr)}")
print(f"Cos{np.cos(arr)}")
print(f"Log{np.log(arr)}")

Sqrt[1.         1.41421356 1.73205081 2.         2.23606798]
Exp[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sin[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cos[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Log[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [34]:
# Array Slicing and Indexing
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
print(arr[0][0])

1


In [39]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [41]:
arr[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [45]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [46]:
# Modify array
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [48]:
arr[1:] = 100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [49]:
# Statistical concepts -- Normalization
# to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])
mean = np.mean(data)
std = np.std(data)
normalized_data = (data - mean) / std
print(normalized_data)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [52]:
data = np.arange(1,11)
print(data)

[ 1  2  3  4  5  6  7  8  9 10]


In [56]:
data[(data > 5) & (data < 8)]

array([6, 7])